apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: default
  # annotations:
  #   hauler.dev/platform: linux/amd64
  #   hauler.dev/registry: docker.io
  #   fluxcd.io/version: 2.4.0
spec:
  images:
    - name: busybox:stable
    - name: postgres:15.8
    - name: traefik/whoami:v1.10
    - name: traefik:v3.2.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: fluxcd
spec:
  images:
    - name: ghcr.io/fluxcd/source-controller:v1.4.1
    - name: ghcr.io/fluxcd/kustomize-controller:v1.4.0
    - name: ghcr.io/fluxcd/helm-controller:v1.1.0
    - name: ghcr.io/fluxcd/notification-controller:v1.4.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: istio
spec:
  images:
    - name: istio/pilot:1.23.3
    - name: istio/proxyv2:1.23.3
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: nginx
spec:
  images:
    - name: ghcr.io/nginxinc/nginx-gateway-fabric/nginx:1.4.0
    - name: ghcr.io/nginxinc/nginx-gateway-fabric:1.4.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: charts
spec:
  charts:
    - name: rancher
      repoURL: https://releases.rancher.com/server-charts/stable
      version: 2.9.2
    - name: cert-manager
      repoURL: https://charts.jetstack.io
      version: v1.16.1
    - name: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      version: 4.11.1
    - name: base
      repoURL: https://istio-release.storage.googleapis.com/charts
      version: 1.23.3
    - name: istiod
      repoURL: https://istio-release.storage.googleapis.com/charts
      version: 1.23.3
    - name: cni
      repoURL: https://istio-release.storage.googleapis.com/charts
      version: 1.23.3
    - name: ztunnel
      repoURL: https://istio-release.storage.googleapis.com/charts
      version: 1.23.3
    - name: istio-ingress
      repoURL: https://istio-release.storage.googleapis.com/charts
      version: 1.23.3
    - name: ngf
      repoURL: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
      version: 1.4.0
    - name: eg
      repoURL: oci://docker.io/envoyproxy/gateway-helm
      version: v1.1.1
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: files
spec:
  files:
    - path: https://fluxcd.io/install.sh
      name: fluxcd-install.sh
    - path: https://get.rke2.io
      name: rke2-install.sh
    - path: hauler-manifest.yaml
